function GIST_data = GISTfile_reader(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GIST20231027115332 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  GIST20231027115332 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  GIST20231027115332 = importfile("C:\Users\nicol\OneDrive\Documents\Research\GVS_Post\GIST_20231027_115332.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Nov-2023 16:47:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Ch1CurrentuA", "Ch1Impedance", "Ch1VoltageV", "Ch2CurrentuA", "Ch2Impedance", "Ch2VoltageV", "Roll", "Pitch", "Yaw"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
GIST_data = readtable(filename, opts);

end